openapi: 3.1.0
info:
  title: Products
  version: '1.0'
  summary: Product management endpoints
  description: Create and manage products.
  contact:
    name: Russ Palermo
    url: Base.do
    email: rjpalermo@Live.com
servers:
  - url: 'http://localhost:3030'
    description: Development
  - url: 'http://v2-invoices-app.dev.vyapay.com'
    description: Staging (API Server)
  - url: 'http://v2-invoices-app.vyapay.com'
    description: Production (API Server)
  - url: 'http://test-api.vyapay.com'
    description: Test (API Gateway)
  - url: 'http://api.vyapay.com'
    description: Production (API Gateway)
paths:
  '/carts/{cart_id}':
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-carts
    post:
      summary: ''
      operationId: post-carts
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/Cart.yaml
    patch:
      summary: ''
      operationId: patch-carts
      responses:
        '200':
          description: OK
      description: ''
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/Cart.yaml
    delete:
      summary: ''
      operationId: delete-carts
      responses: {}
      description: ''
    parameters:
      - $ref: '#/components/parameters/cart_id'
components:
  schemas: {}
  securitySchemes:
    jwt:
      type: http
      scheme: bearer
      description: JWT token received from User Login
    clientKey:
      name: vyalynk-client-id
      type: apiKey
      in: header
      description: API Gateway Merchant Authorization.  Use `10852b2b2f57480696e5a4e918b26cc1` for testing.
    applicationKey:
      name: vyalynk-app-id
      type: apiKey
      in: header
      description: API Gateway Application Authorization.  Use `T6554252567241061980` for testing.
  parameters:
    cart_id:
      name: cart_id
      in: path
      required: true
      schema:
        type: string
        example: cart-yu4r32kbe9d7hu7bbt90l
      description: Cart system record identifier.
security:
  - jwt: []
  - applicationKey: []
    clientKey: []
