openapi: 3.1.0
info:
  title: Invoices
  version: '1.0'
  summary: Invoice management endpoints
  description: Create and manage invoices.
  contact:
    name: Russ Palermo
    url: Base.do
    email: rjpalermo@Live.com
servers:
  - url: 'http://localhost:3030'
    description: Development
  - url: 'http://v2-invoices-app.dev.vyapay.com'
    description: Staging (API Server)
  - url: 'http://v2-invoices-app.vyapay.com'
    description: Production (API Server)
  - url: 'http://test-api.vyapay.com'
    description: Test (API Gateway)
  - url: 'http://api.vyapay.com'
    description: Production (API Gateway)
paths:
  /invoices/templates:
    get:
      summary: List or Fetch Invoice Template by ID
      tags:
        - Templates
      responses: {}
      operationId: get-invoices-templates
      description: |
        1. To list all Invoice Templates associated with merchant account execute request without any additional query paramters
        2.  To fetch an Invoice Template by ID provide the template id (starts with _template-_) as an `invoice_template_id` value.

        | EXPAND AVAILABLE VALUES | DESCRIPTION |
        | :-- | :-- |
        | mid | Expand and return the associated `mid_id` as a **mid** object |
        | contact | Expand and return the associated `contact_id` as a **contact** object |
        | company| Expand and return the associated `company_id` as a **company** object |
        | customer| Expand and return the associated `contact_id` or `company_id` as a **customer** object |
        | cart| Expand and return the associated `cart_id` as a **cart** object |
      parameters:
        - $ref: '#/components/parameters/invoice_template_id'
        - $ref: '#/components/parameters/mid_id'
        - $ref: '#/components/parameters/contact_id'
        - $ref: '#/components/parameters/company_id'
        - $ref: '#/components/parameters/cart_id'
    post:
      summary: Create Invoice Template
      tags: []
      responses: {}
      operationId: post-invoices-templates
    patch:
      summary: Patch Invoice Template
      tags: []
      responses: {}
      operationId: patch-invoices-templates
    delete:
      summary: Remove Invoice Template
      tags: []
      responses: {}
      operationId: delete-invoices-templates
  /invoices:
    get:
      summary: List or Fetch Invoices
      tags:
        - invoices
      responses: {}
      operationId: get-invoices
    post:
      summary: Create an Invoice
      tags:
        - invoices
      responses: {}
      operationId: post-invoices
    patch:
      summary: Patch an Invoice
      tags:
        - invoices
      responses: {}
      operationId: patch-invoices
    delete:
      summary: Remove an Invoice
      tags:
        - invoices
      responses: {}
      operationId: delete-invoices
  /invoices/settings:
    get:
      summary: List or Fetch Invoice Settings
      tags:
        - SETTINGS
      responses: {}
      operationId: get-invoices-settings
      description: ''
    patch:
      summary: Patch Invoice Settings
      tags:
        - SETTINGS
      responses: {}
      operationId: patch-invoices-settings
components:
  schemas: {}
  securitySchemes:
    jwt:
      type: http
      scheme: bearer
      description: JWT token received from User Login
    clientKey:
      name: vyalynk-client-id
      type: apiKey
      in: header
      description: API Gateway Merchant Authorization.  Use `10852b2b2f57480696e5a4e918b26cc1` for testing.
    applicationKey:
      name: vyalynk-app-id
      type: apiKey
      in: header
      description: API Gateway Application Authorization.  Use `T6554252567241061980` for testing.
  parameters:
    name:
      name: name
      in: query
      required: false
      schema:
        type: string
        example: Invoice Template 1
      description: name
    description:
      name: description
      in: query
      required: false
      schema:
        type: string
        example: Custom template for ACME Industries
      description: Description
    id_prefix:
      name: id_prefix
      in: query
      required: false
      schema:
        type: string
        example: ACME-1234
      description: ID prefix
    id_suffix:
      name: id_suffix
      in: query
      required: false
      schema:
        type: string
      description: ID suffix
    cart_id:
      name: cart_id
      in: query
      required: false
      schema:
        type: string
      description: System identifier for cart (starts with `cart-`)
    allow_partial_payment:
      name: allow_partial_payment
      in: query
      required: false
      schema:
        type: boolean
      description: Partial payments enabled
    allow_customer_notes:
      name: allow_customer_notes
      in: query
      required: false
      schema:
        type: boolean
      description: Customer notes enabled
    allow_customer_portal:
      name: allow_customer_portal
      in: query
      required: false
      schema:
        type: boolean
      description: Customer portal enabled
    mid_id:
      name: mid_id
      in: query
      required: false
      schema:
        type: string
      description: System identifier for mid (starts with `mid-`)
    contact_id:
      name: contact_id
      in: query
      required: false
      schema:
        type: string
      description: System identifier for contact (starts with `contact-`)
    company_id:
      name: company_id
      in: query
      required: false
      schema:
        type: string
      description: System identifier for cart (starts with `company-`)
    is_inactive:
      name: is_inactive
      in: query
      required: false
      schema:
        type: boolean
      description: Provide `false` to fetch soft deleted records
    last_request_id:
      name: last_request_id
      in: query
      required: false
      schema:
        type: string
      description: Last created or patched request id
    expand:
      name: expand
      in: query
      required: false
      schema:
        type: string
      description: 'Associated system ID records to fetch and include in response.  See **EXPAND** for available values. '
    fetch:
      name: fetch
      in: query
      required: false
      schema:
        type: string
      description: 'Associated system records to fetch and include in response.  See **FETCH** for available values. '
    invoice_template_id:
      name: invoice_template_id
      in: query
      required: false
      schema:
        type: string
      description: System identifier for invoice template (starts with `template-`)
    invoice_id:
      name: invoice_id
      in: query
      required: false
      schema:
        type: string
      description: System identifier for invoice (starts with `invoice-`)
security:
  - jwt: []
  - applicationKey: []
    clientKey: []
