openapi: 3.1.0
info:
  title: Invoices
  version: '1.0'
  summary: Invoice management endpoints
  description: Create and manage invoices.
  contact:
    name: Russ Palermo
    url: Base.do
    email: rjpalermo@Live.com
servers:
  - url: 'http://localhost:3030'
    description: Development
  - url: 'http://v2-invoices-app.dev.vyapay.com'
    description: Staging (API Server)
  - url: 'http://v2-invoices-app.vyapay.com'
    description: Production (API Server)
  - url: 'http://test-api.vyapay.com'
    description: Test (API Gateway)
  - url: 'http://api.vyapay.com'
    description: Production (API Gateway)
paths:
  /invoices/templates:
    get:
      summary: List or Fetch Invoice Template by ID
      tags:
        - Templates
      responses: {}
      operationId: get-invoices-templates
      description: List Invoice Templates
      parameters:
        - $ref: '#/components/parameters/name'
        - $ref: '#/components/parameters/description'
    post:
      summary: Create Invoice Template
      tags: []
      responses: {}
      operationId: post-invoices-templates
    patch:
      summary: Patch Invoice Template
      tags: []
      responses: {}
      operationId: patch-invoices-templates
    delete:
      summary: Remove Invoice Template
      tags: []
      responses: {}
      operationId: delete-invoices-templates
  /invoices:
    get:
      summary: List or Fetch Invoices
      tags:
        - invoices
      responses: {}
      operationId: get-invoices
    post:
      summary: Create an Invoice
      tags:
        - invoices
      responses: {}
      operationId: post-invoices
    patch:
      summary: Patch an Invoice
      tags:
        - invoices
      responses: {}
      operationId: patch-invoices
    delete:
      summary: Remove an Invoice
      tags:
        - invoices
      responses: {}
      operationId: delete-invoices
components:
  schemas: {}
  securitySchemes:
    jwt:
      type: http
      scheme: bearer
      description: JWT token received from User Login
    clientKey:
      name: vyalynk-client-id
      type: apiKey
      in: header
      description: API Gateway Merchant Authorization.  Use `10852b2b2f57480696e5a4e918b26cc1` for testing.
    applicationKey:
      name: vyalynk-app-id
      type: apiKey
      in: header
      description: API Gateway Application Authorization.  Use `T6554252567241061980` for testing.
  parameters:
    name:
      name: name
      in: query
      required: false
      schema:
        type: string
        example: Invoice Template 1
      description: Invoice template name
    description:
      name: description
      in: query
      required: false
      schema:
        type: string
        example: Custom template for ACME Industries
      description: Invoice template description
    id_prefix:
      name: id_prefix
      in: query
      required: false
      schema:
        type: string
        example: ACME-1234
      description: Invoice ID prefix
    id_suffix:
      name: id_suffix
      in: query
      required: false
      schema:
        type: string
      description: Invoice ID suffix
    cart_id:
      name: cart_id
      in: query
      required: false
      schema:
        type: string
      description: System identifier for cart associated with Invoice Template (starts with `cart-`
    allow_partial_payment:
      name: allow_partial_payment
      in: query
      required: false
      schema:
        type: boolean
      description: Invoice Template partial payments enabled
    allow_customer_notes:
      name: allow_customer_notes
      in: query
      required: false
      schema:
        type: boolean
      description: Invoice Template customer notes enabled
    allow_customer_portal:
      name: allow_customer_portal
      in: query
      required: false
      schema:
        type: boolean
      description: Invoice Template customer portal enabled
security:
  - jwt: []
  - applicationKey: []
    clientKey: []
