openapi: 3.1.0
info:
  title: Payment Engine API
  version: '1.0'
  summary: Payment Engine
  description: Merchant Services API
  contact:
    name: Russ Palermo
    url: Base.do
    email: rjpalermo@live.com
servers:
  - url: 'http://localhost:3030'
    description: Development
  - url: 'http://v2-invoices-app.dev.vyapay.com'
    description: Staging (API Server)
  - url: 'http://v2-invoices-app.vyapay.com'
    description: Production (API Server)
  - url: 'http://test-api.vyapay.com'
    description: Test (API Gateway)
  - url: 'http://api.vyapay.com'
    description: Production (API Gateway)
paths:
  /taxes:
    get:
      summary: Fetch Taxes
      tags:
        - TAX
        - SETTINGS
      responses: {}
      operationId: get-taxes
      description: ''
    post:
      summary: Create Tax
      tags:
        - TAX
        - SETTINGS
      responses: {}
      operationId: post-taxes
    patch:
      summary: Patch Tax
      tags:
        - TAX
        - SETTINGS
      responses: {}
      operationId: patch-taxes
    delete:
      summary: Remove Tax
      tags:
        - TAX
        - SETTINGS
      responses: {}
      operationId: delete-taxes
components:
  schemas: {}
  securitySchemes:
    jwt:
      type: http
      scheme: bearer
      description: JWT token received from User Login
    clientKey:
      name: vyalynk-client-id
      type: apiKey
      in: header
      description: API Gateway Merchant Authorization.  Use `10852b2b2f57480696e5a4e918b26cc1` for testing.
    applicationKey:
      name: vyalynk-app-id
      type: apiKey
      in: header
      description: API Gateway Application Authorization.  Use `T6554252567241061980` for testing.
security:
  - jwt: []
  - applicationKey: []
    clientKey: []
