openapi: 3.1.0
info:
  title: Products
  version: '1.0'
  summary: Cart management endpoints
  description: Create and manage products.
  contact:
    name: Russ Palermo
    url: Base.do
    email: rjpalermo@Live.com
servers:
  - url: 'http://localhost:3030'
    description: Development
  - url: 'http://v2-invoices-app.dev.vyapay.com'
    description: Staging (API Server)
  - url: 'http://v2-invoices-app.vyapay.com'
    description: Production (API Server)
  - url: 'http://test-api.vyapay.com'
    description: Test (API Gateway)
  - url: 'http://api.vyapay.com'
    description: Production (API Gateway)
paths:
  /carts:
    get:
      summary: List or Fetch Carts
      tags:
        - CART
      responses: {}
      operationId: get-carts
    post:
      summary: Create Cart
      tags:
        - CART
      responses: {}
      operationId: post-carts
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/Cart.yaml
            examples:
              System Calculated (full):
                value:
                  name: Cart A
                  description: Cart A Description
                  amount_total: 0
                  amount_subtotal: 0
                  amount_taxes: 0
                  amount_fees: 0
                  amount_discounts: 0
                  amount_costs: 0
                  amount_shipping: 0
                  total_items: 0
                  id_cart: null
                  taxes:
                    total_rate: 20
                    total_amount: 22
                    data:
                      - id: null
                        name: Tax 1
                        description: This is tax 1 description
                        code: T1
                        type: RATE
                        value: 1.5
                        save_tax: false
                      - id: null
                        name: Tax 2
                        description: This is tax 2 description
                        code: T2
                        type: RATE
                        value: 8.5
                        save_tax: true
                      - id: null
                        name: Tax 3
                        description: This is tax 3 description
                        code: T3
                        type: AMOUNT
                        value: 5.55
                        save_tax: true
                  fees:
                    total_rate: 0
                    total_amount: 0
                    data:
                      - id: null
                        name: Fee 1
                        description: This is fee 1 description
                        code: F1
                        type: RATE
                        value: 1.5
                        save_fee: false
                      - id: null
                        name: Fee 2
                        description: This is fee 2 description
                        code: F2
                        type: RATE
                        value: 8.5
                        save_fee: true
                      - id: null
                        name: Fee 3
                        description: This is fee 3 description
                        code: F3
                        type: AMOUNT
                        value: 5.55
                        save_fee: true
                  discounts:
                    total_rate: 0
                    total_amount: 0
                    data:
                      - id: null
                        name: Discount 1
                        description: This is discount 1 description
                        code: D1
                        type: RATE
                        value: 1.5
                        save_discount: false
                      - id: null
                        name: Discount 2
                        description: This is discount 2 description
                        code: D2
                        type: RATE
                        value: 8.5
                        save_discount: true
                      - id: null
                        name: Discount 3
                        description: This is discount 3 description
                        code: D3
                        type: AMOUNT
                        value: 5.55
                        save_discount: true
                  costs:
                    total_rate: 0
                    total_amount: 0
                    data:
                      - id: null
                        name: Cost 1
                        description: This is cost 1 description
                        code: C1
                        type: RATE
                        value: 1.5
                        save_cost: false
                      - id: null
                        name: Cost 2
                        description: This is cost 2 description
                        code: C2
                        type: RATE
                        value: 8.5
                        save_cost: true
                      - id: null
                        name: Fee 3
                        description: This is cost 3 description
                        code: C3
                        type: AMOUNT
                        value: 5.55
                        save_cost: true
                  items:
                    total_rate: 0
                    total_amount: 0
                    data:
                      - id: JJ123980923
                        name: Widget A
                        description: This widget is a good widget
                        image_url: 'https://siteorigin.com/wp-content/themes/siteorigin-theme/pages/widgets-bundle/images/icon.png'
                        unit_price: 12.22
                        unit_cost: 1.55
                        units_sold: 2
                        ignore_tax: false
                        ignore_fees: false
                        ignore_discounts: false
                        ignore_costs: false
                        save_item: true
                      - id: null
                        name: Widget B
                        description: This widget is a not a very good widget
                        image_url: 'https://siteorigin.com/wp-content/themes/siteorigin-theme/pages/widgets-bundle/images/icon.png'
                        unit_price: 16.18
                        unit_cost: 4.12
                        units_sold: 3
                        ignore_tax: false
                        ignore_fees: false
                        ignore_discounts: false
                        ignore_costs: false
                        save_item: true
                  shipping:
                    total: 12
                    carrier: FEDEX
                    tracking: '1234567890'
                    ship_to_address:
                      contact: null
                      street_1: 1446 N. Padre Ln
                      street_2: Suite 4
                      street_3: Bldg 7
                      city: Miami
                      state_code: FL
                      postal_code: '33140'
                      country_code: US
        description: ''
      description: Create a cart of product items
    patch:
      summary: Patch Cart
      tags:
        - CART
      responses: {}
      operationId: patch-carts
    delete:
      summary: Remove Cart
      tags:
        - CART
      responses: {}
      operationId: delete-carts
components:
  schemas: {}
  securitySchemes:
    jwt:
      type: http
      scheme: bearer
      description: JWT token received from User Login
    clientKey:
      name: vyalynk-client-id
      type: apiKey
      in: header
      description: API Gateway Merchant Authorization.  Use `10852b2b2f57480696e5a4e918b26cc1` for testing.
    applicationKey:
      name: vyalynk-app-id
      type: apiKey
      in: header
      description: API Gateway Application Authorization.  Use `T6554252567241061980` for testing.
security:
  - jwt: []
  - applicationKey: []
    clientKey: []
