openapi: 3.1.0
info:
  title: VyaPay OpenAPI 3.1
  version: '1.0'
  summary: VyaPay API
  description: |-
    VyaPay API
  contact:
    name: Technical Support
    url: https://vyapay.com
    email: support@vyapay.com
servers:
  - url: 'http://test-api.vyapay.com'
    description: Test (API Gateway)
  - url: 'http://api.vyapay.com'
    description: Production (API Gateway)
paths: {}
components:
  schemas: {}
  securitySchemes:
    jwt:
      type: http
      scheme: bearer
      description: JWT token received from User Login
    clientKey:
      name: vyalynk-client-id
      type: apiKey
      in: header
      description: API Gateway Merchant Authorization.  Use `10852b2b2f57480696e5a4e918b26cc1` for testing.
    applicationKey:
      name: vyalynk-app-id
      type: apiKey
      in: header
      description: API Gateway Application Authorization.  Use `T6554252567241061980` for testing.
security:
  - jwt: []
  - applicationKey: []
    clientKey: []
